import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  ChevronDown,
  ChevronRight,
  GripVertical,
  MoreHorizontal,
  Plus,
  Trash2,
  Pencil,
  HelpCircle,
  Video,
  FileText,
  Code,
  BookOpen,
} from "lucide-react";
import type { Module, Lesson, Quiz } from "@/lib/course-types";
import { LessonItem, LessonEditor } from "./lesson-editor";
import { QuizEditor } from "./quiz-editor";
import * as api from "@/lib/api";
import { toast } from "sonner";

interface ModuleCardProps {
  courseId: string; // Needed for API calls
  module: Module;
  moduleIndex: number;
  onUpdate: (module: Module) => void;
  onDelete: () => void;
}

export function ModuleCard({ courseId, module, moduleIndex, onUpdate, onDelete }: ModuleCardProps) {
  const [isExpanded, setIsExpanded] = useState(module.isExpanded ?? true);
  const [isEditing, setIsEditing] = useState(false);
  const [editTitle, setEditTitle] = useState(module.title);
  const [editDescription, setEditDescription] = useState(module.description || "");
  
  const [lessonEditorOpen, setLessonEditorOpen] = useState(false);
  const [editingLesson, setEditingLesson] = useState<Lesson | undefined>();
  const [quizEditorOpen, setQuizEditorOpen] = useState(false);

  // ── Module Actions ────────────────────────────────────

  const handleSaveTitle = async () => {
  if (!editTitle.trim()) {
    toast.error("Titlul modulului nu poate fi gol");
    return;
  }

  try {
    // Now 'description' is a known property in the API call
    const updatedModuleData = await api.updateModule(courseId, module.id, { 
      title: editTitle.trim(),
      description: editDescription.trim() 
    });

    onUpdate({ 
      ...module, 
      title: updatedModuleData.title, 
      description: updatedModuleData.description 
    });

    setIsEditing(false);
    toast.success("Modul actualizat");
  } catch (err) {
    toast.error("Eroare la salvarea modulului");
  }
};

  // ── Lesson Actions (Backend Integrated) ───────────────

  const handleSaveLesson = async (lesson: Lesson) => {
    try {
      if (editingLesson) {
        // PUT /api/courses/{courseId}/builder/modules/{moduleId}/lectures/{lectureId}
        const updated = await api.updateLectureInModule(courseId, module.id, lesson.id, {
          title: lesson.title,
          videoUrl: lesson.content,
          durationSecs: (lesson.duration || 0) * 60,
        });
        
        const newLessons = module.lessons.map((l) => (l.id === lesson.id ? lesson : l));
        onUpdate({ ...module, lessons: newLessons });
        toast.success("Lecție actualizată");
      } else {
        // POST /api/courses/{courseId}/builder/modules/{moduleId}/lectures
        const created = await api.addLectureToModule(courseId, module.id, {
          title: lesson.title,
          videoUrl: lesson.content,
          order: module.lessons.length,
          durationSecs: (lesson.duration || 0) * 60,
        });

        // Use the ID generated by the DB
        onUpdate({ ...module, lessons: [...module.lessons, { ...lesson, id: created.id }] });
        toast.success("Lecție adăugată");
      }
    } catch (err) {
      toast.error("Eroare la salvarea lecției");
    }
    setLessonEditorOpen(false);
    setEditingLesson(undefined);
  };

  const handleDeleteLesson = async (lessonId: string) => {
    try {
      await api.deleteLectureFromModule(courseId, module.id, lessonId);
      const newLessons = module.lessons.filter((l) => l.id !== lessonId);
      onUpdate({ ...module, lessons: newLessons });
      toast.success("Lecție ștearsă");
    } catch (err) {
      toast.error("Eroare la ștergerea lecției");
    }
  };

  // ── Quiz Actions ──────────────────────────────────────
  const handleRemoveQuiz = async () => {
    try {
      await api.deleteModuleQuiz(courseId, module.id);
      onUpdate({ ...module, quiz: undefined });
      setQuizEditorOpen(false);
      toast.success("Quiz șters cu succes");
    } catch (err) {
      console.error(err);
      toast.error(err instanceof Error ? err.message : "Eroare la ștergerea quiz-ului");
    }
  };

  const handleSaveQuiz = async (quiz: Quiz) => {
    try {
      const saved = await api.createOrUpdateModuleQuiz(courseId, module.id, {
        title: quiz.title,
        passingScore: quiz.passingScore,
        timeLimit: quiz.timeLimit,
        shuffleQuestions: quiz.shuffleQuestions,
        questions: quiz.questions.map((q) => ({
          text: q.question,
          type: q.type,
          options: q.options || [],
          correctIdx: typeof q.correctAnswer === "number" ? q.correctAnswer : undefined,
          correctText: typeof q.correctAnswer === "string" ? q.correctAnswer : undefined,
          explanation: q.explanation,
        })),
      });
      // Use server-assigned ids so subsequent edits hit the right documents.
      onUpdate({
        ...module,
        quiz: {
          ...quiz,
          id: saved.id,
          questions: quiz.questions.map((q, i) => ({
            ...q,
            id: saved.questions?.[i]?.id || q.id,
          })),
        },
      });
      setQuizEditorOpen(false);
      toast.success("Quiz salvat");
    } catch (err) {
      console.error(err);
      toast.error(err instanceof Error ? err.message : "Eroare la salvarea quiz-ului");
    }
  };

  const totalDuration = module.lessons.reduce((acc, lesson) => acc + (lesson.duration || 0), 0);

  return (
    <>
      <div className="bg-card border border-border rounded-xl sm:rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition-shadow mb-4">
        <div className="p-3 sm:p-4 border-b border-border bg-muted/30">
          <div className="flex items-start gap-2 sm:gap-3">
            <button className="mt-1 cursor-grab text-muted-foreground hover:text-foreground hidden sm:block">
              <GripVertical className="h-5 w-5" />
            </button>
            
            <Collapsible open={isExpanded} onOpenChange={setIsExpanded} className="flex-1">
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1 min-w-0">
                  {isEditing ? (
                    <div className="space-y-2 sm:space-y-3">
                      <Input
                        value={editTitle}
                        onChange={(e) => setEditTitle(e.target.value)}
                        className="font-serif font-semibold text-base sm:text-lg bg-card"
                        autoFocus
                      />
                      <div className="flex gap-2">
                        <Button size="sm" onClick={handleSaveTitle}>Salvează</Button>
                        <Button size="sm" variant="ghost" onClick={() => setIsEditing(false)}>Anulează</Button>
                      </div>
                    </div>
                  ) : (
                    <CollapsibleTrigger className="flex items-center gap-1.5 sm:gap-2 text-left w-full group">
                      {isExpanded ? <ChevronDown className="h-5 w-5" /> : <ChevronRight className="h-5 w-5" />}
                      <div className="min-w-0">
                        <h3 className="font-serif font-semibold text-base sm:text-lg truncate">
                          <span className="text-primary/60 mr-2">{moduleIndex + 1}.</span>
                          {module.title}
                        </h3>
                      </div>
                    </CollapsibleTrigger>
                  )}
                </div>

                {!isEditing && (
                  <div className="flex items-center gap-2">
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="ghost" size="icon"><MoreHorizontal className="h-4 w-4" /></Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuItem onClick={() => setIsEditing(true)}><Pencil className="mr-2 h-4 w-4" /> Redenumire</DropdownMenuItem>
                        <DropdownMenuItem onClick={() => setLessonEditorOpen(true)}><Plus className="mr-2 h-4 w-4" /> Adaugă Lecție</DropdownMenuItem>
                        <DropdownMenuItem onClick={() => setQuizEditorOpen(true)}><HelpCircle className="mr-2 h-4 w-4" /> Quiz</DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem onClick={onDelete} className="text-destructive"><Trash2 className="mr-2 h-4 w-4" /> Șterge</DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                )}
              </div>

              <CollapsibleContent className="mt-4">
                <div className="space-y-2 ml-7">
                  {module.lessons.map((lesson) => (
                    <LessonItem
                      key={lesson.id}
                      lesson={lesson}
                      onEdit={(l) => { setEditingLesson(l); setLessonEditorOpen(true); }}
                      onDelete={handleDeleteLesson}
                    />
                  ))}
                  
                  {module.quiz && (
                    <div className="p-3 bg-primary/10 rounded-xl border border-primary/20 flex items-center justify-between">
                       <div className="flex items-center gap-3">
                         <HelpCircle className="h-4 w-4 text-primary" />
                         <span className="text-sm font-medium">{module.quiz.title}</span>
                       </div>
                       <Button variant="ghost" size="sm" onClick={() => setQuizEditorOpen(true)}><Pencil className="h-4 w-4" /></Button>
                    </div>
                  )}

                  <Button variant="ghost" size="sm" className="w-full mt-2 border-dashed border border-border" onClick={() => setLessonEditorOpen(true)}>
                    <Plus className="h-4 w-4 mr-2" /> Lecție Nouă
                  </Button>
                </div>
              </CollapsibleContent>
            </Collapsible>
          </div>
        </div>
      </div>

      <LessonEditor
        lesson={editingLesson}
        onSave={handleSaveLesson}
        onCancel={() => { setLessonEditorOpen(false); setEditingLesson(undefined); }}
        isOpen={lessonEditorOpen}
      />

      <QuizEditor
        quiz={module.quiz}
        onSave={handleSaveQuiz}
        onCancel={() => setQuizEditorOpen(false)}
        onRemove={() => handleRemoveQuiz()} // Wrap it in an arrow function here
        isOpen={quizEditorOpen}
      />
    </>
  );
}